# Fill in the blanks below and rename this file to user_settings.py
# Keep this template up-to-date with any changes to the required environment variables below

ENV_PATH: str = ...  # Path to build executable (e.g. path/to/AnimalAI.app for Mac)
CLAUDE_API_KEY: str = ...
GPT_API_KEY: str = ...
GEMINI_API_KEY: str = ...
LOG_FOLDER: str = ...